name: leafy_launcher
description: A new Flutter project.

publish_to: 'none'

version: 1.2.4

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^5.2.1
  ensure_initialized: ^0.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_oss_licenses: ^1.1.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.8
  get: ^4.5.1
  intl: ^0.17.0
  lint: ^1.8.1
  logger: ^1.0.0
  moor_flutter: ^4.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  synchronized: ^3.0.0
  table_calendar: ^3.0.2
  url_launcher: ^6.0.18
  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  moor_generator: ^4.6.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
